version: "3"

services:
  flarum:
    image: mondedie/flarum:latest
    container_name: flarum
    env_file:
      - ./flarum.env
    volumes:
      - ./app/assets:/flarum/app/public/assets
      - ./app/extensions:/flarum/app/extensions
      - ./app/storage/logs:/flarum/app/storage/logs
      - ./nginx:/etc/nginx/flarum
    ports:
      - 8088:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Xd2iQbB7uQeS
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=Xd2iQbB7uQeS
    volumes:
      - ./mysql/db:/var/lib/mysql
