<?php
return array (
  'danmuplayer' => 
  array (
    'status' => '1',
    'sort' => '1800',
    'from' => 'danmuplayer',
    'show' => '弹幕播放器',
    'des' => '基于dplayer的弹幕播放器，支持m3u8和mp4',
    'parse' => '/index.php/danmu/player?url=',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'danmuplayer',
  ),
  '1080zyk' => 
  array (
    'status' => '1',
    'from' => '1080zyk',
    'show' => '优质资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1231',
    'tip' => '无需安装任何插件',
    'id' => '1080zyk',
  ),
  'jinyingm3u8' => 
  array (
    'status' => '1',
    'from' => 'jinyingm3u8',
    'show' => '金鹰资源②',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1224',
    'tip' => '无需安装任何插件',
    'id' => 'jinyingm3u8',
  ),
  'jinyingyun' => 
  array (
    'status' => '1',
    'from' => 'jinyingyun',
    'show' => '金鹰云①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1223',
    'tip' => '无需安装任何插件',
    'id' => 'jinyingyun',
  ),
  'kcm3u8' => 
  array (
    'status' => '1',
    'from' => 'kcm3u8',
    'show' => '快车资源①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1221',
    'tip' => '无需安装任何插件',
    'id' => 'kcm3u8',
  ),
  'ukm3u8' => 
  array (
    'status' => '1',
    'from' => 'ukm3u8',
    'show' => '弹幕播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1211',
    'tip' => '无需安装任何插件',
    'id' => 'ukm3u8',
  ),
  'fsyun' => 
  array (
    'status' => '1',
    'from' => 'fsyun',
    'show' => '飞速云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1209',
    'tip' => '无需安装任何插件',
    'id' => 'fsyun',
  ),
  'fsm3u8' => 
  array (
    'status' => '1',
    'from' => 'fsm3u8',
    'show' => '飞速播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1208',
    'tip' => '无需安装任何插件',
    'id' => 'fsm3u8',
  ),
  'sdm3u8' => 
  array (
    'status' => '1',
    'from' => 'sdm3u8',
    'show' => '闪电播放',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1207',
    'tip' => '无需安装任何插件',
    'id' => 'sdm3u8',
  ),
  'sdyun' => 
  array (
    'status' => '1',
    'from' => 'sdyun',
    'show' => '闪电云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1206',
    'tip' => '无需安装任何插件',
    'id' => 'sdyun',
  ),
  'if101' => 
  array (
    'status' => '1',
    'from' => 'if101',
    'show' => 'if101',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1202',
    'tip' => '无需安装任何插件',
    'id' => 'if101',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '无尽①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1194',
    'tip' => '无需安装任何插件',
    'id' => 'wjm3u8',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => '红牛在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1193',
    'tip' => '无需安装任何插件',
    'id' => 'hnm3u8',
  ),
  'tkm3u8' => 
  array (
    'status' => '1',
    'from' => 'tkm3u8',
    'show' => '天空在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1111',
    'tip' => '无需安装任何插件',
    'id' => 'tkm3u8',
  ),
  'tkyun' => 
  array (
    'status' => '1',
    'from' => 'tkyun',
    'show' => '天空云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1110',
    'tip' => '无需安装任何插件',
    'id' => 'tkyun',
  ),
  'lezy' => 
  array (
    'status' => '1',
    'from' => 'lezy',
    'show' => '乐库云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1072',
    'tip' => '无需安装任何插件',
    'id' => 'lezy',
  ),
  'dbm3u8' => 
  array (
    'status' => '1',
    'from' => 'dbm3u8',
    'show' => '百度在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1033',
    'tip' => '无需安装任何插件',
    'id' => 'dbm3u8',
  ),
  'bjm3u8' => 
  array (
    'status' => '1',
    'from' => 'bjm3u8',
    'show' => '八戒在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1023',
    'tip' => '无需安装任何插件',
    'id' => 'bjm3u8',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1006',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'PPTV视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1005',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1004',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1003',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://z1.m1907.top/?jx=',
    'sort' => '1002',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'ddzy' => 
  array (
    'status' => '1',
    'from' => 'ddzy',
    'show' => '多多播放1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'ddzy',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'xigua' => 
  array (
    'status' => '1',
    'from' => 'xigua',
    'show' => '西瓜视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '997',
    'tip' => '无需安装任何插件',
    'id' => 'xigua',
  ),
  'bilibili' => 
  array (
    'status' => '1',
    'from' => 'bilibili',
    'show' => '哔哩哔哩',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '995',
    'tip' => '无需安装任何插件',
    'id' => 'bilibili',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://movie.matrices.cf/resolve/jx/v.php?url=',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
);